networks: (( merge ))

meta:
  environment: ~

  release:
    name: cf

  networks:
    z1:
      apps: cf1
      management: cf1


  loggregator_endpoint:
    z1:
      host: (( jobs.loggregator_trafficcontroller_z1.networks.cf1.static_ips.[0] || nil ))

  nfs_server: ~

jobs:
  - name: api 
    release: (( meta.release.name ))
    template: (( merge || ["haproxy", "gorouter", "cloud_controller_ng"] ))
    instances: 0
    resource_pool: medium
    networks:
      - name: cf1
        static_ips: ~
    properties:
      networks: (( meta.networks.z1 ))
      ccdb: ccdb
      loggregator_endpoint:
        host: (( meta.loggregator_endpoint.z1.host ))
      ha_proxy:
        ssl_pem: ~
      router:
        servers:
          z1: (( jobs.api.networks.cf1.static_ips ))
      nfs_server: (( meta.nfs_server ))

  - name: nats_z1
    release: (( meta.release.name ))
    template: (( merge || ["nats", "nats_stream_forwarder"] ))
    instances: 1
    resource_pool: medium
    networks:
      - name: cf1
        static_ips: (( merge ))
    properties:
      networks: (( meta.networks.z1 ))

  - name: logs_z1
    release: (( meta.release.name ))
    template: syslog_aggregator
    instances: 0
    resource_pool: medium
    persistent_disk: 100000
    networks:
      - name: cf1
        static_ips: (( merge ))
    properties:
      networks: (( meta.networks.z1 ))

  - name: stats_z1
    release: (( meta.release.name ))
    template: collector
    instances: 1
    resource_pool: small
    networks:
      - name: cf1
    properties:
      networks: (( meta.networks.z1 ))

  - name: data 
    release: (( meta.release.name ))
    template: (( merge || ["postgres", "debian_nfs_server"] ))
    instances: 0
    resource_pool: medium
    persistent_disk: 102400
    networks:
      - name: cf1
        static_ips: ~
    properties:
      db: databases


  - name: uaa_z1
    release: (( meta.release.name ))
    template: (( merge || ["uaa", "login"] ))
    instances: 1
    resource_pool: medium
    networks:
      - name: cf1
    properties:
      networks: (( meta.networks.z1 ))

  - name: api_worker_z1
    release: (( meta.release.name ))
    template: cloud_controller_ng
    instances: 1
    resource_pool: small
    persistent_disk: 0
    networks:
      - name: cf1
    properties:
      ccdb: ccdb
      networks: (( meta.networks.z1 ))
      loggregator_endpoint:
        host: (( meta.loggregator_endpoint.z1.host ))
      ccng:
        process_group: worker
      nfs_server: (( meta.nfs_server ))


  - name: hm_z1
    release: (( meta.release.name ))
    template: health_manager_next
    instances: 0
    resource_pool: medium
    networks:
      - name: cf1
    properties:
      networks: (( meta.networks.z1 ))

  - name: etcd_z1
    release: (( meta.release.name ))
    template: etcd
    instances: 1
    persistent_disk: 10024
    resource_pool: medium
    networks:
      - name: cf1
        static_ips:  (( merge ))
    properties:
      networks: (( meta.networks.z1 ))

  - name: runner
    release: (( meta.release.name ))
    template: (( merge || ["dea_next", "dea_logging_agent"] ))
    instances: 1
    update:
      max_in_flight: 1
    resource_pool: medium
    networks:
      - name: cf1
        static_ips: ~
    properties:
      networks: (( meta.networks.z1 ))
      loggregator_endpoint:
        host: (( meta.loggregator_endpoint.z1.host ))

  - name: loggregator_z1
    release: (( meta.release.name ))
    template: (( merge || ["loggregator" || "loggregator_trafficcontroller"] ))
    instances: 1
    resource_pool: medium
    networks:
      - name: cf1
        static_ips: (( merge ))
    properties:
      networks: (( meta.networks.z1 ))
      traffic_controller:
        zone: z1



properties:
  domain: (( merge ))
  ssl:
    skip_cert_verify: (( merge || false ))
  system_domain: (( domain ))
  system_domain_organization: ~
  app_domains: (( [domain] ))

  disk_quota_enabled: true

  request_timeout_in_seconds: 300

  nats:
    user: (( merge ))
    password: (( merge ))
    address: (( jobs.nats_z1.networks.cf1.static_ips.[0] ))
    machines: (( jobs.nats_z1.networks.cf1.static_ips ))
    port: 4222
    use_gnatsd: (( merge || true ))
    debug: false
    trace: false

  dea_next:
    memory_mb: (( merge ))
    memory_overcommit_factor: 3
    disk_mb: (( merge ))
    disk_overcommit_factor: 2
    staging_disk_inode_limit: 200000
    instance_disk_inode_limit: 200000
    deny_networks: (( merge || [] ))
    allow_networks: (( merge || [] ))
    kernel_network_tuning_enabled: true
    directory_server_protocol: https
    evacuation_bail_out_time_in_seconds: 600

  loggregator_endpoint:
    shared_secret: (( merge ))

  logger_endpoint: ~

  loggregator:
    servers:
      z1: (( jobs.loggregator_z1.networks.cf1.static_ips ))
    maxRetainedLogMessages: 100
    debug: (( merge || false ))
    blacklisted_syslog_ranges: ~

  cc: (( merge ))
  ccdb: (( merge ))

  ccng: (( cc ))
  ccdb_ng: (( ccdb ))

  uaa: (( merge ))
  uaadb: (( merge ))

  databases: ~

  login: (( merge ))

  router:
    status:
      user: (( merge ))
      password: (( merge ))

  syslog_aggregator: ~

  nfs_server:
    address: (( jobs.data.networks.cf1.static_ips.[0] || nil ))
    network: (( networks.cf1.subnets.[0].range ))

  collector:
    use_datadog: true
    datadog_api_key: ""
    datadog_application_key: ""
    deployment_name: (( meta.environment ))
    use_tsdb: false

  opentsdb: (( merge || nil ))
