name: cf-1393242361
director_uuid: 160c2c3e-26ce-4fe7-93eb-83af3e9d8652

releases:
 - name: cf
   version: 149

networks:
#- name: floating
#  type: vip
#  cloud_properties: {}
- name:  default
  subnets:
  - range: 10.0.0.0/24
    reserved:
    - 10.0.0.2 - 10.0.0.9
    static:
    - 10.0.0.10 - 10.0.0.99
    gateway: 10.0.0.1
    dns:
    - 10.0.0.3 
    cloud_properties:
      name: VM Network 2

update:
  canaries: 1
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 4

compilation:
  workers: 1 
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    ram: 4096
    disk: 16368
    cpu: 1 

resource_pools:
  - name: small
    network: default
    size: 3
    stemcell:
      name: bosh-vsphere-esxi-ubuntu
      version: latest
    cloud_properties:
        ram: 1024
        disk: 2048
        cpu: 1
  - name: medium
    network: default
    size: 1
    stemcell:
      name: bosh-vsphere-esxi-ubuntu
      version: latest
    cloud_properties:
        ram: 4096
        disk: 16468
        cpu: 2 

jobs:
  - name: data
    release: cf
    template:
      - postgres
      - debian_nfs_server
    instances: 1
    resource_pool: small
    persistent_disk: 4096
    networks:
    - name: default
      static_ips:
      - 10.0.0.11
    properties:
      db: databases

  - name: core
    release: cf
    template:
      - nats
      - health_manager_next
      - uaa
    instances: 1
    resource_pool: small
    networks:
    - name: default
      static_ips:
      - 10.0.0.12

  - name: api
    release: cf
    template:
      - cloud_controller_ng
      - gorouter
    instances: 1
    resource_pool: small
    networks:
    - name: default
      static_ips:
      - 10.0.0.10
  #  properties:
  #    db: databases

  - name: dea
    release: cf
    template:
      - dea_next
    instances: 1
    resource_pool: medium
    persistent_disk: 32768
    networks:
      - name: default
        static_ips:
        - 10.0.0.13

properties:
  cf:
    name: cf-1393242361
    dns: api.goettecf.io 
    ip_addresses: ["10.0.0.10"]
    deployment_size: medium
    security_group: default
    persistent_disk: 4096
    common_password: 7f7b072987bf
    dea_server_ram: 1500

  domain: goettecf.io 
  system_domain: goettecf.io 
  system_domain_organization: system_domain
  app_domains:
    - goettecf.io 

  networks:
    apps: default
    management: default

  nats:
    address: 0.core.default.cf-1393242361.microbosh
    machines:
    - 0.core.default.cf-1393242361.microbosh
    port: 4222
    user: nats
    password: 7f7b072987bf
    authorization_timeout: 5

  router:
    port: 8081
    status:
      port: 8080
      user: gorouter
      password: 7f7b072987bf

  dea: &dea
    memory_mb: 1500
    disk_mb: 10240
    directory_server_protocol: http

  dea_next: *dea

  nfs_server:
    address: 0.data.default.cf-1393242361.microbosh
    network: "*.cf-1393242361.microbosh"
    idmapd_domain: api.goettecf.io

  debian_nfs_server:
    no_root_squash: true

  databases: &databases
    db_scheme: postgres
    address: 0.data.default.cf-1393242361.microbosh
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: 7f7b072987bf
      - tag: admin
        name: uaaadmin
        password: 7f7b072987bf
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

  ccdb: &ccdb
    db_scheme: postgres
    address: 0.data.default.cf-1393242361.microbosh
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: 7f7b072987bf
    databases:
      - tag: cc
        name: ccdb
        citext: true

  ccdb_ng: *ccdb

  uaadb: 
    db_scheme: postgresql
    address: 0.data.default.cf-1393242361.microbosh
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: 7f7b072987bf
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  cc_api_version: v2

  cc: &cc
    logging_level: debug
    external_host: api
    srv_api_uri: http://api.goettecf.io
    cc_partition: default
    db_encryption_key: 7f7b072987bf
    bootstrap_admin_email: admin@10.0.0.10.xip.io
    bulk_api_password: 7f7b072987bf
    uaa_resource_id: cloud_controller
    staging_upload_user: uploaduser
    staging_upload_password: 7f7b072987bf
    resource_pool:
      resource_directory_key: cc-resources
      # Local provider when using NFS
      fog_connection:
        provider: Local
    packages:
      app_package_directory_key: cc-packages
    droplets:
      droplet_directory_key: cc-droplets
    default_quota_definition: runaway

  ccng: *cc

  login:
    enabled: false

  uaa:
    url: http://uaa.goettecf.io
    spring_profiles: postgresql
    no_ssl: true
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    resource_id: account_manager
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: 7f7b072987bf
    admin:
      client_secret: 7f7b072987bf
    batch:
      username: batchuser
      password: 7f7b072987bf
    client:
      autoapprove:
        - cf
    clients:
      cf:
        override: true
        authorized-grant-types: password,implicit,refresh_token
        authorities: uaa.none
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
        access-token-validity: 7200
        refresh-token-validity: 1209600
    scim:
      users:
      - admin|7f7b072987bf|scim.write,scim.read,openid,cloud_controller.admin
      - services|7f7b072987bf|scim.write,scim.read,openid,cloud_controller.admin
